version: "2.1"

services:

  # http://127.0.0.1:1011
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  # http://127.0.0.1:8080 (alastria/alastria)
  grafana-oss:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 8080:3000
    environment:
      - GF_SECURITY_ADMIN_USER=change_me
      - GF_SECURITY_ADMIN_PASSWORD=change_me
    user: '0'
    logging:
      options:
        max-size: 1g
    restart: unless-stopped
